name: Docker Build and Test

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      
      - name: Lowercase owner
        id: lowercase
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: cookie-analyzer:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          # Simple test to verify the image runs
          docker run --rm cookie-analyzer:${{ github.sha }} --help || echo "Command returned non-zero, but container started"
          
      # GitHub Container Registry push removed for now to avoid authentication issues
      # Uncomment when ready to push to GitHub Container Registry
      # - name: Login to GitHub Container Registry
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # 
      # - name: Push to GitHub Container Registry
      #   if: github.event_name != 'pull_request'
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ghcr.io/${{ env.OWNER_LC }}/cookie-analyzer:latest
      #       ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/cookie-analyzer:{1}', env.OWNER_LC, github.ref_name) || '' }}
      #     cache-from: type=gha