name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint black isort mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check code formatting with Black
      run: black --check cookie_analyzer tests
      
    - name: Check import sorting with isort
      run: isort --check-only --profile black cookie_analyzer tests
      
    - name: Lint with flake8
      run: flake8 cookie_analyzer tests
      
    - name: Lint with pylint
      run: pylint --disable=C0111,C0103,C0303,W1201,W1202,C0200,W0612,R0913,R0914 cookie_analyzer tests