name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: bump_version
        run: |
          bump_type=${{ github.event.inputs.bump_type }}
          # Get current version before bump
          PREVIOUS_VERSION=$(grep -Po "__version__ = \"\K[^\"]+" cookie_analyzer/__init__.py)
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
          
          # Run bumpversion
          bumpversion --commit --tag $bump_type
          
          # Get new version after bump
          NEW_VERSION=$(grep -Po "__version__ = \"\K[^\"]+" cookie_analyzer/__init__.py)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_TAG=v$NEW_VERSION" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git push --follow-tags origin HEAD:${GITHUB_REF}

      # Using newer softprops/action-gh-release instead of deprecated actions/create-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: |
            ## What's Changed
            * Automated version bump to v${{ env.NEW_VERSION }}
            
            ## Full Changelog
            https://github.com/${{ github.repository }}/compare/v${{ env.PREVIOUS_VERSION }}...v${{ env.NEW_VERSION }}